// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package xc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// XcServiceClient is the client API for XcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XcServiceClient interface {
	GetExchangeAmount(ctx context.Context, in *GetExchangeAmountRequest, opts ...grpc.CallOption) (*GetExchangeAmountResponse, error)
	PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error)
}

type xcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewXcServiceClient(cc grpc.ClientConnInterface) XcServiceClient {
	return &xcServiceClient{cc}
}

func (c *xcServiceClient) GetExchangeAmount(ctx context.Context, in *GetExchangeAmountRequest, opts ...grpc.CallOption) (*GetExchangeAmountResponse, error) {
	out := new(GetExchangeAmountResponse)
	err := c.cc.Invoke(ctx, "/xc.XcService/GetExchangeAmount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xcServiceClient) PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error) {
	out := new(PlaceOrderResponse)
	err := c.cc.Invoke(ctx, "/xc.XcService/PlaceOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XcServiceServer is the server API for XcService service.
// All implementations must embed UnimplementedXcServiceServer
// for forward compatibility
type XcServiceServer interface {
	GetExchangeAmount(context.Context, *GetExchangeAmountRequest) (*GetExchangeAmountResponse, error)
	PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error)
	mustEmbedUnimplementedXcServiceServer()
}

// UnimplementedXcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedXcServiceServer struct {
}

func (UnimplementedXcServiceServer) GetExchangeAmount(context.Context, *GetExchangeAmountRequest) (*GetExchangeAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExchangeAmount not implemented")
}
func (UnimplementedXcServiceServer) PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceOrder not implemented")
}
func (UnimplementedXcServiceServer) mustEmbedUnimplementedXcServiceServer() {}

// UnsafeXcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XcServiceServer will
// result in compilation errors.
type UnsafeXcServiceServer interface {
	mustEmbedUnimplementedXcServiceServer()
}

func RegisterXcServiceServer(s grpc.ServiceRegistrar, srv XcServiceServer) {
	s.RegisterService(&XcService_ServiceDesc, srv)
}

func _XcService_GetExchangeAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExchangeAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XcServiceServer).GetExchangeAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xc.XcService/GetExchangeAmount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XcServiceServer).GetExchangeAmount(ctx, req.(*GetExchangeAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XcService_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XcServiceServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xc.XcService/PlaceOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XcServiceServer).PlaceOrder(ctx, req.(*PlaceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// XcService_ServiceDesc is the grpc.ServiceDesc for XcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xc.XcService",
	HandlerType: (*XcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExchangeAmount",
			Handler:    _XcService_GetExchangeAmount_Handler,
		},
		{
			MethodName: "PlaceOrder",
			Handler:    _XcService_PlaceOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trading/proto/xc/xc.proto",
}
