// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package wallet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletServiceClient interface {
	CreateTradingTransaction(ctx context.Context, in *CreateTradingRequest, opts ...grpc.CallOption) (*CreateTradingResponse, error)
	ConfirmTransaction(ctx context.Context, in *ConfirmTransactionRequest, opts ...grpc.CallOption) (*ConfirmTransactionResponse, error)
	RejectTransaction(ctx context.Context, in *ConfirmTransactionRequest, opts ...grpc.CallOption) (*ConfirmTransactionResponse, error)
}

type walletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServiceClient(cc grpc.ClientConnInterface) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) CreateTradingTransaction(ctx context.Context, in *CreateTradingRequest, opts ...grpc.CallOption) (*CreateTradingResponse, error) {
	out := new(CreateTradingResponse)
	err := c.cc.Invoke(ctx, "/wallet.WalletService/CreateTradingTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ConfirmTransaction(ctx context.Context, in *ConfirmTransactionRequest, opts ...grpc.CallOption) (*ConfirmTransactionResponse, error) {
	out := new(ConfirmTransactionResponse)
	err := c.cc.Invoke(ctx, "/wallet.WalletService/ConfirmTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) RejectTransaction(ctx context.Context, in *ConfirmTransactionRequest, opts ...grpc.CallOption) (*ConfirmTransactionResponse, error) {
	out := new(ConfirmTransactionResponse)
	err := c.cc.Invoke(ctx, "/wallet.WalletService/RejectTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
// All implementations must embed UnimplementedWalletServiceServer
// for forward compatibility
type WalletServiceServer interface {
	CreateTradingTransaction(context.Context, *CreateTradingRequest) (*CreateTradingResponse, error)
	ConfirmTransaction(context.Context, *ConfirmTransactionRequest) (*ConfirmTransactionResponse, error)
	RejectTransaction(context.Context, *ConfirmTransactionRequest) (*ConfirmTransactionResponse, error)
	mustEmbedUnimplementedWalletServiceServer()
}

// UnimplementedWalletServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWalletServiceServer struct {
}

func (UnimplementedWalletServiceServer) CreateTradingTransaction(context.Context, *CreateTradingRequest) (*CreateTradingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTradingTransaction not implemented")
}
func (UnimplementedWalletServiceServer) ConfirmTransaction(context.Context, *ConfirmTransactionRequest) (*ConfirmTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmTransaction not implemented")
}
func (UnimplementedWalletServiceServer) RejectTransaction(context.Context, *ConfirmTransactionRequest) (*ConfirmTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectTransaction not implemented")
}
func (UnimplementedWalletServiceServer) mustEmbedUnimplementedWalletServiceServer() {}

// UnsafeWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServiceServer will
// result in compilation errors.
type UnsafeWalletServiceServer interface {
	mustEmbedUnimplementedWalletServiceServer()
}

func RegisterWalletServiceServer(s grpc.ServiceRegistrar, srv WalletServiceServer) {
	s.RegisterService(&WalletService_ServiceDesc, srv)
}

func _WalletService_CreateTradingTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTradingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).CreateTradingTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.WalletService/CreateTradingTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).CreateTradingTransaction(ctx, req.(*CreateTradingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ConfirmTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ConfirmTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.WalletService/ConfirmTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ConfirmTransaction(ctx, req.(*ConfirmTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_RejectTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).RejectTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.WalletService/RejectTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).RejectTransaction(ctx, req.(*ConfirmTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletService_ServiceDesc is the grpc.ServiceDesc for WalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTradingTransaction",
			Handler:    _WalletService_CreateTradingTransaction_Handler,
		},
		{
			MethodName: "ConfirmTransaction",
			Handler:    _WalletService_ConfirmTransaction_Handler,
		},
		{
			MethodName: "RejectTransaction",
			Handler:    _WalletService_RejectTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trading/proto/wallet/wallet.proto",
}
